site_name: Grassroots Users Documentation
site_url: https://grassroots.tools
docs_dir: docs
theme:
  name:  material
  custom_dir: overrides
  logo: assets/logo-white.png
  palette:
    - scheme: grassroots
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: grey
      accent: purple

    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
extra:
    homepage: https://grassroots.tools/documentation/
    
    
    

extra_css:
  - stylesheets/extra.css


plugins:
  - mkdocstrings
  - search
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
use_directory_urls: false  

nav:
  - Home: index.md
  - Field Trials:
      - Introduction:         services/field_trial/index.md
      - Submitting Data:
        - Obtaining an ORCID: services/field_trial/orcid.md
        - Submitting Programmes: services/field_trial/submit_programme.md
        - Submitting Trials:     services/field_trial/submit_trial.md
        - Submitting Locations:     services/field_trial/submit_location.md
        - Submitting Studies:   services/field_trial/submit_study.md
        - Submitting Plots:     services/field_trial/submit_plots.md
        - Submitting Measured Variables:     services/field_trial/submit_measured_variables.md
      
      - Searching & Visualising Data:
        - Main Field Trials Portal:  services/field_trial/fieldtrials_general_table.md
        - Plot Data:     services/field_trial/fieldtrials_study_table.md
        - Heatmaps:     services/field_trial/heatmaps.md
        - Field Trials Search Portal:   services/field_trial/search_portal.md        
        - Measured Phenotype variables: services/field_trial/search_measured_variables.md
        - Treatments:                   services/field_trial/search_treatments.md
      - Download Data:
        - Frictionless Data Package: services/field_trial/download_study_fd.md 
        - CSV File: services/field_trial/download_study_CSV.md 
  - General Search Service:
      - Introduction:         services/general_search/index.md      
 
  - BLAST Service:
      - Introduction:         services/blast/index.md      
  - ' ': ' '
  - ' ': ' '
  - Installation (Developers):
      - 'Building grassroots core':   services/installation/readme.md
      - 'Sample database':            services/installation/getting_started.md
  - ' ': ' '
  - ' ': ' '
  - Mobile App (beta version):
    - General Browsing & Data Submission: mobile_app/index.md
    - QR Scanner (in development): mobile_app/scanning.md

