site_name: Grassroots Users Documentation
site_url: http://localhost:2000/grassroots/
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo-white.png
  palette:
    - scheme: grassroots
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: grey
      accent: purple

    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
extra:
    homepage: https://grassroots.tools/documentation
    
    
    

extra_css:
  - stylesheets/extra.css


plugins:
  - mkdocstrings
  - search
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Field Trials:
      - Introduction:         field_trial/index.md
      - Submitting Data:
        - Obtaining an ORCID: field_trial/orcid.md
        - Submitting Programmes: field_trial/submit_programme.md
        - Submitting Trials:     field_trial/submit_trial.md
        - Submitting Locations:     field_trial/submit_location.md
        - Submitting Studies:   field_trial/submit_study.md
        - Submitting Plots:     field_trial/submit_plots.md
        - Submitting Measured Variables:     field_trial/submit_measured_variables.md
      
      - Searching & Visualising Data:
        - Main Field Trials Portal:  field_trial/fieldtrials_general_table.md
        - Plot Data:     field_trial/fieldtrials_study_table.md
        - Heatmaps:     field_trial/heatmaps.md
        - Field Trials Search Portal:   field_trial/search_portal.md        
        - Measured Phenotype variables: field_trial/search_measured_variables.md
        - Treatments:                   field_trial/search_treatments.md
      - Download Data:
        - Frictionless Data Package: field_trial/download_study_fd.md 
        - CSV File: field_trial/download_study_CSV.md 
  - General Search Service:
      - Introduction:         general_search/index.md      
 
  - BLAST Service:
      - Introduction:         BLAST/index.md      
  - ' ': ' '
  - ' ': ' '
  - Installation (Developers):
      - 'Building grassroots core':   installation/readme.md
      - 'Sample database':            installation/getting_started.md
  - ' ': ' '
  - ' ': ' '
  - Mobile App (beta version):
    - General Browsing & Data Submission: mobile_app/index.md
    - QR Scanner (in development): mobile_app/QR.md
